name: 'Install Atlassian SDK'
author: rodrigo-nogues
description: 'Download Atlassian SDK and install it'
branding:
  icon: server
  color: blue
runs:
  using: "composite"
  steps:
    - run: |
        sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >> /etc/apt/sources.list'
        wget https://packages.atlassian.com/api/gpg/key/public
        sudo apt-key add public
        sudo apt-get update
        sudo apt-get install atlassian-plugin-sdk=8.2.7
        atlas-version
      shell: bash
